version: "3"
services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  postgres:
    networks:
      - backend
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  worker1:
    networks:
      - backend
    image: scripter51/worker
    ports:
      - "8082:8082"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]

  master1:
    networks:
      - backend
    image: scripter51/master
    ports:
      - "8081:8081"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  backend:

volumes:
  db-data:
