version: "3"
services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  mysql:
    networks:
      - backend
    image: mysql
    ports: 
      - "3306:3306"
    volumes:
      - db_data2:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_ROOT_PASSWORD: ThePassword

  worker1:
    networks:
      - backend
    image: scripter51/worker
    ports:
      - "8082:8082"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]

  master1:
    networks:
      - backend
    image: scripter51/master
    ports:
      - "8081:8081"

networks:
  backend:
    external:
      name: mynetwork2

volumes:
  db_data2:
